language: python
jobs:
  - name: "Python 3.8 on Linux"
    python: 3.8 # this works on Linux but not Windows or MacOS. Default Python in Travis-CI is 3.6.
  - name: "Python 3.7.4 on MacOS"
    is: osx
    osx_image: xcode11.2 # Python 3.7.4 running on MacOS 10.14.4
    language: shell # this is instead of python which is an error in MacOS Travis-CI for some reason
  - name: "Python 3.8.0 on Windows"
    os: windows # Windows 10.0.17134 N/A Build 17134
    language: shell # this is instead of python which is an error in Windows Travis-CI for some reason
    before_install:
      - choco install python --version 3.8.0
      - python -m pip install --upgrade pip
    env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
#python:
#  - "3.6"
#  - "3.7"
virtualenv:
  system_site_package: false
install:
  - pip install -r requirements.txt
script:
  - pytest
